### ISSUE TITLE
Installation on Python3

### ISSUE THREAD

**Issue by Bawbd** [skyride/avrse-auth#2]
Hello,

I'd like to try the auth system on python3, I tried quickly before going to work but I had some issues like:

> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1fc88066a8>
> (...)
>   File "/home/kawik/venv/auth/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 198, in get_new_connection
>     conn = Database.connect(**conn_params)
> TypeError: 'charset' is an invalid keyword argument for this function

I'll dig into that later tonight when I'm back home.

Also would you write a very quick step by step guide on how to install it?

Not something very specific, just the basic steps. I already installed Alliance Auth so it shouldn't be much different but a short guide would be great in my opinion.

Could this work with mariadb instead of sqlite?

Thank you in advance for the help.

**Comment by skyride** [comment]
I'd recommend against Python 3 for now until I fully test and move to it, but if you checkout the python3 branch it should work.

The error you're getting is because you're using sqlite instead of mysql.

Also mysql/maria are mostly interchangeable.

**Comment by Bawbd** [comment]
Alright, I'm just testing right now using MySQL.

I got it working but after login and authorize a character I get a "Server Error (500)".

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/weakref.py", line 117, in remove
> TypeError: 'NoneType' object is not callable
> Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f06041a4ae8>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/weakref.py", line 117, in remove
> TypeError: 'NoneType' object is not callable
> 
> Unicode-objects must be encoded before hashing
> 
> esi.py in request, line 67

I guess I'll wait for you to test it more on Python 3 before posting about it.

**Comment by Bawbd** [comment]
With the same settings but Python2.7 the error is this one:

> Authentication process canceled
