### ISSUE TITLE
manage.py migrate fails with 'Group has no details.'

### ISSUE THREAD

**Issue by atkinsj** [skyride/avrse-auth#7]
Been a while since I've pulled from HEAD and a migrate fails with:

```
Applying eveauth.0052_add_groups...Traceback (most recent call last):
[..]
  File "/opt/auth/avrse-auth/eveauth/migrations/0052_add_groups.py", line 15, in add_groups
    logistics.details.is_open = False
django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: Group has no details.
```

Do you happen to know offhand what I need to manually update in the database to fix this?

**Comment by skyride** [comment]
Hey yeah it was just a thing I didn't test properly.

If you make 2 groups called Logistics and Audit (case sensitive) then
re-run the migration it should be fine.

**Comment by atkinsj** [comment]
sorted it, cheers.
