### ISSUE TITLE
Migration Error(s)

### ISSUE THREAD

**Issue by Cephalostrum** [skyride/avrse-auth#8]
When doing the initial migration, django throws an error that access_level column is not in eveauth_groupdetails table. Manually adding access_level allows the migration to continue.

Also, even after adding the recommended 'admin' and 'fc' columns to eveauth_groupdetails and auth_group, migration fails on 0052_add_groups line 15 
"logistics.details.is_open = False" 
and throws the error
"django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: Group has no details."

**Comment by skyride** [comment]
Hi friend, this issue should now be resolved as of a recent update!
